pull_request_rules:
- name: dependabot-auto-merge
  description: Automatically merge dependabot PRs that pass CI
  conditions:
    - author=dependabot[bot]
    - check-success=npm-lint
    - check-success=Shellcheck
    - check-success=markdown-lint
    - check-success=DCO
    - label!=hold
  actions:
    merge:
      method: merge

- name: auto-merge
  description: automatic merge for main with > 1 approved reviews, all requested reviews have given feedback, not held, and CI is successful
  conditions:
    - "#approved-reviews-by>=1"
    - "#review-requested=0"
    - "#changes-requested-reviews-by=0"
    - base=main
    - label!=hold
    - check-success=npm-lint
    - check-success=Shellcheck
    - check-success=markdown-lint
    - check-success=DCO
  actions:
    merge:
      method: merge
