name: UI lint

on:
  push:
    branches: ["main"]
    paths:
      - '.github/workflows/lint-ui.yml'
      - 'ui/*'
      - '!ui/README.md'
  pull_request:
    branches: ["main"]
    paths:
      - '.github/workflows/lint-ui.yml'
      - 'ui/*'
      - '!ui/README.md'
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  npm-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: ui
      - name: Run UI linting
        run: npm run lint
        working-directory: ui
      - name: Run UI type check
        run: npm run type-check
        working-directory: ui
